# NMF

In [1]:
import numpy as np

In [9]:
X = np.array([
    [2, 1, 3],
    [4, 1, 1],
    [1, 3, 3]
])
W = np.array([
    [1, 1],
    [1, 1],
    [1, 1]
])

H = np.array([
    [1, 1, 1],
    [1, 1, 1]
])


In [20]:
def update_H(X: np.ndarray, W: np.ndarray, H: np.ndarray) -> np.ndarray:
    newH = H * ( (W.T @ X) / (W.T @ W @ H) )
    return newH


In [33]:
def update_W(X: np.ndarray, W: np.ndarray, H: np.ndarray) -> np.ndarray:
    newH = W * ( (X @ H.T) / (W @ H @ H.T) )
    return newH


In [29]:
n = 3
p = 3
r = 2

In [31]:
W = np.random.rand(n, r)
H = np.random.rand(r, p)

In [51]:
max_iter = 1000
eps = 1e-10

k=0
convergence = False
while k < max_iter and not(convergence):
    newH = update_H(X, W, H)
    newW = update_W(X, W, newH)
    convergenceH = (np.linalg.norm(newH-H) < eps)
    convergenceW = (np.linalg.norm(newW-W) < eps)
    convergence = (convergenceH and convergenceW)
    H, W = newH, newW

print(f"Original data : \n{X}")
print(f"Reconstructed data : \n{W@H}")
print(f"Squared reconstruction error : {np.linalg.norm(W@H - X)}")


Original data : 
[[2 1 3]
 [4 1 1]
 [1 3 3]]
Reconstructed data : 
[[2.04460348 1.75955104 2.40682674]
 [3.98347707 0.71863165 1.21973531]
 [0.97394333 2.55628187 3.34652277]]
Squared reconstruction error : 1.1730853739924236


In [37]:
from sklearn.decomposition import NMF

In [39]:
nmf = NMF(n_components=2)
nmf.fit(X)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/decomposition/_nmf.py:289: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  warnings.warn(


NMF(n_components=2)

In [54]:
print(f"Original data : \n {X}")
print(f"Reconstructed data : \n {nmf.fit_transform(X)}")
print(f"Squared reconstruction error : {nmf.reconstruction_err_}")


Original data : 
 [[2 1 3]
 [4 1 1]
 [1 3 3]]
Reconstructed data : 
 [[1.24116015 0.75767399]
 [0.50700297 2.04552421]
 [1.80304119 0.        ]]
Squared reconstruction error : 1.1730853884067822


/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/decomposition/_nmf.py:289: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  warnings.warn(
